#!/usr/bin/env node
// Builds a release APK.
//
// The build does not happen in this directory, and that is not a preference:
// ninja is not long-path aware, and the C++ steps in Reanimated and
// react-native-screens fail on a path this deep. So the sources that affect the
// bundle are mirrored into a short path and Gradle is run there.
//
// Usage:
//   node scripts/build-android.js                       # every ABI, timestamped
//   node scripts/build-android.js --abi x86_64 \
//        --env .env.e2e --out builds/e2e-x86_64.apk     # the emulator build
//
// The default output name carries a timestamp because these are handed to people
// to install, and two files called `app-release.apk` are indistinguishable once
// they are on a phone.

const { execFileSync, spawnSync } = require('node:child_process');
const { copyFileSync, existsSync, mkdirSync, statSync } = require('node:fs');
const path = require('node:path');

const ROOT = path.join(__dirname, '..');
/** Short enough for ninja. Holds its own `android/` and `node_modules/`. */
const SHORT = process.env.ANDROID_BUILD_DIR ?? 'C:\\fa';

/**
 * What actually changes the app.
 *
 * The whole of `android/` now, minus what the build generates. Copying only
 * `android/app/src` was not enough twice over: a manifest change never reached
 * the build once, and adding `google-services.json` needs the Gradle files that
 * `expo prebuild` rewrites — the plugin that reads it is declared there.
 */
const MIRRORED_DIRS = ['src', 'assets', 'scripts', 'plugins', '.maestro', 'android'];
/**
 * Kept out of the mirror: generated by the build, and enormous.
 *
 * Excluded rather than copied, which is also what preserves the incremental
 * build — `robocopy /MIR` deletes anything in the destination that is missing
 * from the source, and these exist only in the destination.
 */
const NOT_MIRRORED = ['build', '.gradle', '.cxx', '.kotlin', 'node_modules'];
const COPIED_FILES = [
  'app.json',
  'package.json',
  'tsconfig.json',
  '.env',
  'eslint.config.js',
  // Read by the Gradle plugin `expo prebuild` declares once `googleServicesFile`
  // is set. Absent, the build produces an app that cannot reach FCM.
  'google-services.json',
];

function fail(message) {
  console.error(`\n${message}\n`);
  process.exit(1);
}

function step(label) {
  console.log(`\n=== ${label} ===`);
}

function robocopy(from, to) {
  // 1 and 3 are "files copied" and "extra files removed" — both are success.
  const result = spawnSync(
    'robocopy',
    [from, to, '/MIR', '/NFL', '/NDL', '/NJH', '/NJS', '/NP', '/XD', ...NOT_MIRRORED],
    { encoding: 'utf8', shell: true },
  );
  if ((result.status ?? 0) > 7) {
    fail(`robocopy failed for ${from}:\n${result.stdout}\n${result.stderr}`);
  }
}

function main() {
  const args = process.argv.slice(2);
  const abi = args.includes('--abi') ? args[args.indexOf('--abi') + 1] : null;
  // `EXPO_PUBLIC_API_URL` is inlined into the bundle at build time, so which API
  // a build talks to is decided here and nowhere else. The override is written as
  // the build directory's own `.env`, which leaves this repository's untouched.
  const envFile = args.includes('--env') ? args[args.indexOf('--env') + 1] : '.env';
  const out = args.includes('--out')
    ? args[args.indexOf('--out') + 1]
    : path.join('builds', `foxacademy-${stampName()}.apk`);

  if (!existsSync(SHORT)) {
    fail(
      `${SHORT} does not exist.\n` +
        '  It holds the Android project and node_modules for the build. Create it by\n' +
        '  copying this repository there once, then this script keeps it in step.',
    );
  }

  step('1/3 mirroring the sources');
  for (const dir of MIRRORED_DIRS) {
    robocopy(path.join(ROOT, dir), path.join(SHORT, dir));
  }
  for (const file of COPIED_FILES) {
    const from = path.join(ROOT, file);
    if (existsSync(from)) copyFileSync(from, path.join(SHORT, file));
  }
  if (envFile !== '.env') {
    const from = path.join(ROOT, envFile);
    if (!existsSync(from)) fail(`No such env file: ${envFile}`);
    copyFileSync(from, path.join(SHORT, '.env'));
    console.log(`using ${envFile} as the build's .env`);
  }
  console.log('sources in step');

  step('2/3 clearing the bundle output');
  // Gradle treats the bundle task as up to date on inputs it does not track, so
  // a JS-only change can otherwise ship the previous bundle inside a new APK.
  // Built from path segments rather than a literal: a Windows path in a source
  // file is one backslash away from being a string escape.
  for (const generated of [
    path.join(SHORT, 'android', 'app', 'build', 'generated', 'assets'),
    path.join(SHORT, 'android', 'app', 'build', 'intermediates', 'assets'),
  ]) {
    spawnSync('cmd', ['/c', 'rmdir', '/s', '/q', generated], { shell: true });
  }
  console.log('cleared');

  step(`3/3 assembling${abi ? ` for ${abi}` : ''}`);
  execFileSync(
    path.join(SHORT, 'android', 'gradlew.bat'),
    ['assembleRelease', ...(abi ? [`-PreactNativeArchitectures=${abi}`] : [])],
    { stdio: 'inherit', shell: true, cwd: path.join(SHORT, 'android') },
  );

  const built = path.join(SHORT, 'android', 'app', 'build', 'outputs', 'apk', 'release', 'app-release.apk');
  if (!existsSync(built)) fail(`Gradle reported success but ${built} is missing.`);

  const target = path.join(ROOT, out);
  mkdirSync(path.dirname(target), { recursive: true });
  copyFileSync(built, target);

  const megabytes = (statSync(target).size / 1024 / 1024).toFixed(1);
  console.log(`\n${out}  ${megabytes} MB`);
}

/** `20260824-0512`, in local time — these are read by whoever installs them. */
function stampName() {
  const now = new Date();
  const pad = (value) => String(value).padStart(2, '0');
  return (
    `${now.getFullYear()}${pad(now.getMonth() + 1)}${pad(now.getDate())}` +
    `-${pad(now.getHours())}${pad(now.getMinutes())}`
  );
}

main();
